<h2> Group List</h2>
<div class="row">
    <div class="col-sm-5">
<?php
echo $result;
// $result generated by admin_view/list_group
?></div>
</div>
<a href="/admin/admin_view/create_group" class="btn btn-info">New group</a>
<a href="/admin/admin_view" class="btn btn-default">Cancel</a>
