<!--data from user/index 
    calls user functions
-->
<h2>User List</h2>
<div class="row">
    <div class="col-sm-5">
<?php
echo $result;
//result generated by controller admin_view/list_users.  Table generated in function with edit and delete butons with IDs


?></div>
</div>
<a href="/admin/admin_view/create_user" class="btn btn-info">New user</a>
<a href="/admin/admin_view" class="btn btn-default">Cancel</a>